name: Go Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Add permissions for the SARIF upload
permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        run: go build -v -o k8s-controller

      - name: Test
        run: go test -v
      
      - name: Run Trivy for code scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          timeout: '5m'

      - name: Run Trivy scan (SARIF output)
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-go'

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: k8s-controller
          path: k8s-controller
          retention-days: 7